# Шрифты с иконками
#
- src: https://github.com/ctorgalson/ansible-role-nerdfonts

# Устанавливаем релизы из github
#
- src: https://github.com/ctorgalson/ansible-role-github-release

# Устанавливаем fnm
#
- src: https://github.com/hurricanehrndz/ansible-fnm
