#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: download ai files

export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)
export BASE=$(basename $BIN)

AGENTS_DIR=$DIR/aid.d

py() {
  python3 $DIR/aid.py $@
}

list_agents() {
  echo "shed"

  if py nomad; then
    echo "shed-nomad"
  fi
}

get_clipboard() {
  xsel -o 2>/dev/null
  echo ""
}

load_content() {
  CLIPBOARD=$(get_clipboard)

  for agent in $(list_agents); do
    . "$DIR/aid.d/$agent" "$CLIPBOARD"
  done
}

watch_content() {
  info "Watching clipboard for changes"
  while true; do
    sleep 5
    CLIPBOARD=$(get_clipboard)
    LINES=$(echo -e "$CLIPBOARD" | wc -l)
    FIRST_LINE=$(echo -e "$CLIPBOARD" | head -n1)

    if [[ "$CLIPBOARD" != "$OLD_CLIPBOARD" ]]; then
      debug "Clipboard changed"
      COLS=$(echo "$COLUMNS - 14" | bc)
      debug "${FIRST_LINE:0:$COLS}"
      load_content
      OLD_CLIPBOARD=${CLIPBOARD}
      debug "done updating"
    fi
  done
}

usage() {
  echo " $ $BASE         # process clipboard once
 $ $BASE ls      # list available processors
 $ $BASE w[atch] # process clipboard on each change
 $ $BASE <name>  # edit processor script"
}

case "$1" in
"") load_content ;;
"ls") list_agents | sed "s/^/ * /" ;;
"w" | "watch") watch_content ;;
"h" | "--help" | "help") usage ;;
*) $EDITOR $DIR/aid.d/$1 ;;
esac
