#!/bin/bash

list_commands() {
  echo "nc      | ctrl+p"
  echo "mocp    | ctrl+i"
  echo "gd conf | ctrl+o"
  echo "x       | ctrl+x"
  echo "cfg run | ctrl+c"
  echo "ax f    | alt+a"
  echo "ax sync"
}

ITEM=$(list_commands | fzf | sed "s/|.*$//")

if [[ "$ITEM" != "" ]]; then
  eval "$ITEM"
fi
