#!/bin/bash

list_commands() {
  echo "nc      | ctrl+i"
  echo "mocp    | ctrl+o"
  echo "ax f    | alt+a"
  echo "ax sync"
}

ITEM=$(list_commands | fzf | sed "s/|.*$//")

if [[ "$ITEM" != "" ]]; then
  eval "$ITEM"
fi
