#!/bin/bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: Browse url from stdin or first parameter
#
# Dependencies:
#  * browse cmd
#  * read from bash

usage() {
  echo "# Browse to first parameter or stdin"
  echo ""
  echo " $ echo https://google.com | b   # open google.com"
  echo " $ b https://google.com          # same thing"
}

main() {
  URL="$1"

  [[ "$1" == "" ]] && read URL
  [[ "$URL" != "" ]] && browse $URL
}

case "$1" in
"h" | "help") usage ;;
*) main $@ ;;
esac
