#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: choose from list with fzf from terminal
#   but with rofi -dmenu from gui
#

choose_with_fzf() {
  FZF_PROMPT=
  IGNORE_CASE=

  # skip rofi flags
  if [[ "$1" == "-i" ]]; then
    IGNORE_CASE="-i"
    shift
  fi
  if [[ "$1" == "-matching" ]]; then
    shift
    shift
  fi
  if [[ "$1" == "-p" ]]; then
    FZF_PROMPT=$2
    shift
    shift
  elif [[ "$PROMPT" != "" ]]; then
    # Prompt with spaces from another script
    FZF_PROMPT=$PROMPT
  fi

  if [[ -z "${FZF_PROMPT}" ]]; then
    FZF_PROMPT=">"
  fi

  fzf $IGNORE_CASE --prompt "$FZF_PROMPT " $@
}

choose_with_rofi() {
  rofi -dmenu -matching normal $@
}

if [[ "$TERM" == "screen-256color" ]]; then
  choose_with_fzf $@
else
  choose_with_rofi $@
fi
