#!/usr/bin/env bash

BIN="$(readlink -f $0)"
BASE="$(basename $BIN)"

# Where collecting json is placed
json_file() {
  FJ="$(var fragmentJson)"
  [[ "$FJ" == "" ]] && (
    mkdir -p "$HOME/var"
    FJ="$HOME/var/fragments.json"
    echo "$FJ"
  ) || echo "$FJ"
}

list_names() {
  FJ="$(json_file)"
  if [ -f $FJ ]; then
    cat "$FJ" | jq -r .[].filename
  fi
}

remove_file() {
  FJ="$(json_file)"
  if [[ "$1" != "" ]]; then
    KEY="$(list_names | grep "$1" | head -n1)"
    if [[ "$KEY" != "" ]]; then
      jq --arg key "$KEY" 'del(.[$key])' "$FJ" >"${FJ}.tmp" && mv "${FJ}.tmp" "$FJ"
    fi
  fi
}

cat_file() {
  FJ="$(json_file)"
  if [[ "$1" != "" ]]; then
    KEY="$(list_names | grep "$1" | head -n1)"
    if [[ "$KEY" != "" ]]; then
      jq -r --arg key "$KEY" '.[$key].text | join("\n")' "$FJ"
    fi
  fi
}

edit_fragment() {
  FJ="$(json_file)"
  if [[ "$1" != "" ]]; then
    KEY="$(list_names | grep "$1" | head -n1)"
    if [[ "$KEY" != "" ]]; then
      FILE="$(jq -r --arg key "$KEY" '.[$key].filename' "$FJ")"
      cat_file "$KEY" >"/tmp/$FILE"
      $EDITOR "/tmp/$FILE"
    fi
  fi
}

markdown() {
  FJ="$(json_file)"

  jq -r '
    to_entries[] |
    "## \(.value.filename):\(.value.lines.from)-\(.value.lines.to)\n\n```\(.value.filename)\n\(.value.text | join("\n"))\n```\n"
  ' "$FJ"
}

usage() {
  echo " $ $BASE h[elp]   # show this text"
  echo " $ $BASE base     # get current file to keep fragments"
  echo " $ $BASE ls|list  # list already added filenames"
  echo " $ $BASE e[dit]   # open added file to fix"
  echo " $ $BASE rm       # remove filename"
  echo " $ $BASE md       # output markdown"
  echo " $ $BASE          # select then edit file"
}

case "$1" in
"h" | "help") usage ;;
"base") json_file ;;
"ls" | "list") list_names ;;
"cat")
  shift
  cat_file $@
  ;;
"e" | "edit")
  shift
  edit_fragment $@
  ;;
"rm")
  shift
  remove_file $@
  ;;
"md" | "markdown")
  shift
  markdown $@
  ;;
"")
  KEY="$(list_names | fzf)"
  if [[ "$KEY" != "" ]]; then
    edit_fragment "$KEY"
  fi
  ;;
esac
