#!/usr/bin/env python3
import re
import sys

line = sys.stdin.readline()
if line:
    cleaned = re.sub(r"[^a-z ]", "", line.rstrip("\n").lower())
    print(cleaned.strip()[0:40], end="")
else:
    print("", end="")
