#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: proj replacement
#
# Dependencies:
#  * fzf
#  * jq
#

CONFIG_FILE=$HOME/var/dir.json
EDITOR=nvim

usage() {
  echo " » Go to Dir and..."
  echo ""
  echo " $ gd .                      # add current dir to list"
  echo " $ gd add nemo               # add current dir with command"
  echo " $ gd <name fragment>        # find dir and open with command"
  echo " $ gd e[dit]                 # edit directories file"
  echo " $ gd f                      # output config file"
  echo " $ gd                        # display full list and select with fzf"
  echo " $ gd h[elp]                 # show this text"
}

output_config() {
  cat $CONFIG_FILE
}

add_directory() {
  DIR=$1
  BIN=${2:-${EDITOR}}
  URL="$(xsel -ob)"
  NAME=$(basename $DIR)

  COUNT="$(echo $URL | grep 'http' | wc -l)"
  if [[ "$COUNT" == "0" ]]; then
    URL=""
  fi

  if [[ "$URL" != "" ]]; then
    BIN="open"
    NAME="site:${URL}"
    output_config |
      jq -M ".[\"$NAME\"].url=\"$URL\"|.[\"$NAME\"].bin=\"$BIN\"" \
        >$CONFIG_FILE.new
  else
    output_config |
      jq -M ".[\"$NAME\"].dir=\"$DIR\"|.[\"$NAME\"].bin=\"$BIN\"" \
        >$CONFIG_FILE.new
  fi

  # Otherwise jq will remove all file content
  mv $CONFIG_FILE.new $CONFIG_FILE
}

edit_config_file() {
  echo "[DEBUG] Editor: $EDITOR, Config: $CONFIG_FILE"
  $EDITOR $CONFIG_FILE
}

create_config_file() {
  mkdir -p $(dirname $CONFIG_FILE)
  echo "{}" >$CONFIG_FILE
}

ensure_config_file() {
  [ ! -f $CONFIG_FILE ] && create_config_file
}

list_titles() {
  output_config | jq -r 'keys | join("\n")'
}

fzf_directory() {
  if [[ "$@" != "" ]]; then
    TARGET=$(list_titles | fzf -1 -q $@)
  else
    TARGET=$(list_titles | fzf)
  fi

  if [[ "$TARGET" != "" ]]; then
    DIR=$(output_config | jq -r ".[\"${TARGET}\"].dir")
    URL=$(output_config | jq -r ".[\"${TARGET}\"].url")
    BIN=$(output_config | jq -r ".[\"${TARGET}\"].bin")

    if [[ "${URL}" != "null" ]]; then
      eval "$BIN $URL"
    elif [ -d $DIR ]; then
      cd $DIR && eval "$BIN ." && cd - >/dev/null
    elif [ -f $DIR ]; then
      eval "$BIN $DIR"
    fi
  fi
}

ensure_config_file

case "$1" in
"h" | "help") usage ;;
"e" | "edit") edit_config_file ;;
"f") output_config ;;
"." | "add") add_directory $PWD $2 ;;
"ls" | "list") list_titles ;;
"") fzf_directory ;;
*) fzf_directory $@ ;;
esac
