#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: initialize git remository
#   add remote into github
#   push into remote

if [ ! -d ./.git ]; then
  echo " * Initialize git repository"
  git init &>/dev/null
fi

if [ -f ./.gitignore ]; then
  echo " ! Setup file .gitignore and run again"
  exit 1
fi

REPO=$(basename $(pwd))
INITIALIZED="$(git remote -v 2>/dev/null | wc -l)"

initial_commit() {
  git add .
  git commit -m "Initial commit"

  echo " * Push repository to remote"
  git push -u origin master
}

if [[ "$INITIALIZED" == "0" ]]; then
  REPO_NAME="$USER/$REPO"
  gh repo create "$REPO_NAME" --private

  echo " * Add origin remote"
  git remote add origin "git@github.com:$REPO_NAME.git"

  initial_commit
elif [[ "$FORCED" == "true" ]]; then
  initial_commit
fi
