#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: launcher
#
# Dependencies:
#  * xdotool
#  * fzf
#

## bootstrap
export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)

export LAUNCH_DIR=$DIR/launch.d
## bootstrap

start_or_activate_by_classname() {
  BINARY=$1
  CLASSNAME=$2

  WINID=$(xdotool search --classname "$CLASSNAME" | tail -n1)

  if [[ "$WINID" == "" ]]; then
    $BINARY &
  else
    xdotool windowactivate $WINID
  fi
}

list_commands() {
  cd $LAUNCH_DIR && ls -1 && cd - >/dev/null
}

launch_last() {
  # LAST=$(history 1 | sed 's/^[[:space:]]*//')
  LAST_DIR=$(fasd -l | tail -n1)
  eval "cd $LAST_DIR && fc -s"
}

case "$1" in
"last")
  launch_last
  ;;
"ls" | "list")
  list_commands
  ;;
"")
  CMD=$(list_commands | $HOME/bin/chooser)
  [[ "$CMD" != "" ]] && . $LAUNCH_DIR/$CMD
  ;;
*)
  [ -f $LAUNCH_DIR/$1 ] && . $LAUNCH_DIR/$1
  ;;
esac
