#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: launcher
#
# Dependencies:
#  * xdotool
#  * fzf
#

## bootstrap
export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)

export LAUNCH_DIR=$DIR/launch.d
## bootstrap

__list_windows() {
  for x in $1; do
    title=$(xdotool getwindowname $x)
    echo "$x $title"
  done
}

start_or_select_from_list() {
  BINARY=$1
  CLASSNAME=$2
  PROMPT=$3

  CONTENT=$(xdotool search --class $CLASSNAME)
  COUNT="$(echo "$CONTENT" | sed "s/ *$//" | grep -v "^$" | wc -l)"

  if [[ "$COUNT" == "0" ]]; then
    "$BINARY"
  elif [[ "$COUNT" == "1" ]]; then
    xdotool windowactivate "$CONTENT"
  else
    OUTPUT=$(__list_windows "$CONTENT" | rofi -dmenu $PROMPT)
    WID=$(echo "$OUTPUT" | sed "s/ .*$//")
    xdotool windowactivate "$WID"
  fi
}

start_or_activate_by_classname() {
  BINARY=$1
  CLASSNAME=$2

  WINID=$(xdotool search --classname "$CLASSNAME" | tail -n1)

  if [[ "$WINID" == "" ]]; then
    $BINARY &
  else
    xdotool windowactivate $WINID
  fi
}

list_commands() {
  cd $LAUNCH_DIR && ls -1 && cd - >/dev/null
}

launch_last() {
  # LAST=$(history 1 | sed 's/^[[:space:]]*//')
  LAST_DIR=$(fasd -l | tail -n1)
  eval "cd $LAST_DIR && fc -s"
}

case "$1" in
"last")
  launch_last
  ;;
"ls" | "list")
  list_commands
  ;;
"")
  CMD=$(list_commands | $HOME/bin/chooser)
  [[ "$CMD" != "" ]] && . $LAUNCH_DIR/$CMD
  ;;
*)
  [ -f $LAUNCH_DIR/$1 ] && . $LAUNCH_DIR/$1
  ;;
esac
