#!/usr/bin/env bash

export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)
export DDIR="$DIR/note.d"
export BITS_REPO="git@github.com:kaineer/bits.git"
export BITS_DIR="$HOME/git/bits"

fzf_then_edit() {
  FILTER="$1"

  cd $BITS_DIR
  if [[ "$FILTER" == "" ]]; then
    FILE=$(fd -tf | fzf --preview='bat --color=always -p -lmd {}')
  else
    FILE=$(fd -tf | fzf --exact --preview='bat --color=always -p -lmd {}' -1 -q"$FILTER")
  fi
  if [[ "$FILE" != "" ]]; then
    $EDITOR $FILE
  fi
}

case "$1" in
"new") source "$DDIR/new_note" ;;
"clone") source "$DDIR/clone_repo" ;;
"sync")
  shift
  REPO_DIR="${BITS_DIR}" source "$DDIR/sync" $@
  ;;
"bro" | "browse")
  cd $BITS_DIR
  gh browse
  ;;
"x")
  cd "$BITS_DIR"
  shift
  eval "$@"
  ;;
"f")
  shift
  fzf_then_edit $@
  ;;
"y" | "year")
  fzf_then_edit "$(date +%Y/)"
  ;;
"m" | "mon" | "month")
  fzf_then_edit "$(date +%Y/%m)"
  ;;
"d" | "kyou")
  fzf_then_edit "$(date +%Y/%m%d)"
  ;;
"h" | "help")
  bat -p -lmd $DDIR/help.md
  ;;
"rg")
  cd $BITS_DIR && nvim +":Telescope live_grep"
  ;;
"")
  cd $BITS_DIR
  fzf_then_edit
  [[ "$FILE" != "" ]] && nvim $FILE
  ;;
esac
