#!/usr/bin/env bash

export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)
export DDIR="$DIR/note.d"
export BITS_REPO="git@github.com:kaineer/bits.git"
export BITS_DIR="$HOME/git/bits"

fzf_then_edit() {
  FILTER="$1"

  echo "$PATH"

  cd $BITS_DIR
  export FZF_DEFAULT_OPTS="--preview 'bat --color=always'"
  if [[ "$FILTER" == "" ]]; then
    FILE=$(fd -tf | fzf)
  else
    FILE=$(fd -tf | fzf -1 -q"$FILTER")
  fi
  if [[ "$FILE" != "" ]]; then
    $EDITOR $FILE
  fi
}

case "$1" in
"new") source "$DDIR/new_note" ;;
"clone") source "$DDIR/clone_repo" ;;
"sync")
  shift
  export DF_DIR="$BITS_DIR"
  source "$DDIR/sync" $@
  ;;
"bro" | "browse")
  cd $BITS_DIR
  gh browse
  ;;
"x")
  cd "$BITS_DIR"
  shift
  eval "$@"
  ;;
"f")
  shift
  fzf_then_edit $@
  ;;
"y" | "year")
  fzf_then_edit "$(date +%Y/)"
  ;;
"m" | "mon" | "month")
  fzf_then_edit "$(date +%Y/%m)"
  ;;
"d" | "kyo")
  fzf_then_edit "$(date +%Y/%m%d)"
  ;;
"")
  cd $BITS_DIR
  FILE=$(fd -tf | fzf)
  [[ "$FILE" != "" ]] && nvim $FILE
  ;;
esac
