#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: open dir with $EDITOR from terminal
#   but with nemo from gui
#

open_with_editor() {
  $EDITOR $@
}

open_with_nemo() {
  nemo $@
}

case "$TERM" in
  *-256color)
    open_with_editor $@
    ;;
  *)
    open_with_nemo $@
    ;;
esac

