#!/bin/bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: runs npm/pnpm/yarn
#
# Dependencies:
#   $ROOT/.pm file

REG_LIST_ROOT="$HOME/var/pm/registries"
[ ! -d "$REG_LIST_ROOT" ] && mkdir -p "$REG_LIST_ROOT"

BIN0="$(readlink -f $0)"

usage() {
  clear
  echo ":: Package manager shortcut"
  echo ""
  echo " $ pm init              # create package.json"
  echo " ------------------------------------------------------"
  echo " $ pm h[elp]            # show this help"
  echo " $ pm ri|reinstall      # remove node_modules, $PM install"
  echo " $ pm use npm|pnpm|yarn # choose package manager"
  echo " $ pm ver[sion]         # select version"
  echo "                        #   and put into .node-version"
  echo " $ pm clean             # remove dist and node_modules dirs"
  echo " $ pm ls                # list package managers"
  echo " $ pm r[egistry] ...    # registry commands"
  echo " $ pm r ls              # list available registries"
  echo " $ pm r <registry url>  # set registry"
  echo " $ pm r select          # list registries, select and set"
  echo " $ pm r                 # print current registry url"
  echo " $ pm [anything]        # $PM [anything]"
}

if [ ! -f "$PWD/package.json" ]; then
  if [[ "$1" == "init" ]]; then
    npm init --yes
  elif [[ "$1" != "h" ]]; then
    echo " ! pm command is available only in package directory"
    exit
  fi
fi

PM="npm"
LCFGFILE="$PWD/.pm"

if [ -f "$LCFGFILE" ]; then
  PM=$(cat "$LCFGFILE")
fi

set_node_version() {
  fnm use "$1"
  node --version >"$PWD/.node-version"
}

use_package_manager() {
  case "$1" in
  "npm" | "pnpm" | "yarn")
    echo "$1" >"$LCFGFILE"
    echo " * Set pm to $1"
    ;;
  "")
    N=$(pm ls | fzf)
    pm use "$N"
    ;;
  *) ;;
  esac
}

list_package_managers() {
  [[ "$(which npm)" != "" ]] && echo "npm"
  [[ "$(which pnpm)" != "" ]] && echo "pnpm"
  [[ "$(which yarn)" != "" ]] && echo "yarn"
}

display_info() {
  echo "Name: $(cat package.json | jq -r .name)"
  [ -f ./.node-version ] && echo "Node: $(cat ./.node-version)" || echo " > run «pm ver 20» for example"
  [ -f ./.pm ] && echo "  Pm: $(cat ./.pm)" || echo " > run «pm use npm» for example"
}

reinstall_directory() {
  rm -rf node_modules
  $PM install --force
}

cleanup_directory() {
  rm -rf node_modules
  rm -rf dist
}

_list_registries() {
  cd $REG_LIST_ROOT && cat * && cd - &>/dev/null
}

list_registries() {
  _list_registries | sed "s/^/ * /"
}

set_current_registry() {

  if curl -s -f -o /dev/null "$1"; then
    ALREADY_FOUND="$(_list_registries | grep \"$1\" | wc -l)"
    if [[ "$ALREADY_FOUND" != "0" ]]; then
      UUID="$(uuidgen)"
      echo "$1" > "$REG_LIST_ROOT/$UUID"
    fi
    echo "registry=$1" > "$HOME/.npmrc"
  else
    echo "Url is not available"
  fi
}

show_current_registry() {
  cat "$HOME/.npmrc" | sed "s/^.*=//"
}

select_registry() {
  REG_URL="$(_list_registries | fzf)"
  if [[ "$REG_URL" != "" ]]; then
    set_current_registry "$REG_URL"
  fi
}

registry_command() {
  case "$1" in
    "ls" | "list") list_registries ;;
    "s" | "select") select_registry ;;
    "") show_current_registry ;;
    *) set_current_registry $@ ;;
  esac
}

case "$1" in
"ri" | "reinstall")
  yn -p "Remove installed modules and install again?" \
    reinstall_directory
  ;;
"harakiri" | "clean")
  yn -p "Remove dist and node_modules directories?" \
    cleanup_directory
  ;;
"" | "h" | "help")
  usage | bat -p -lsh
  ;;
"use")
  shift
  use_package_manager $@
  ;;
"ver" | "version")
  shift
  set_node_version "$@"
  ;;
"info")
  display_info
  ;;
"ls" | "list")
  list_package_managers
  ;;
"r" | "registry")
  shift
  registry_command $@
  ;;
*)
  $PM "$@"
  ;;
esac
