#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: Run some commands by domain name
#

_usage() {
  echo "## THE WHAT"
  echo "\`\`\`sh"
  echo " $ the path      # all parts of current executables path"
  echo " $ the net       # address of current available network"
  echo " $ the uname     # uname active parts"
  echo " $ the arch      # architecture for binaries"
  echo " $ the kill      # kill selected process"
  echo "\`\`\`"
}

echo_usage() {
  if [[ "$(which bat)" == "" ]]; then
    _usage
  else
    _usage | bat -lmd -p
  fi
}

echo_path() {
  echo "$PATH" | sed "s/:/\\n/g" | grep -v "^$"
}

echo_net() {
  NETS="$(ip a | grep -E '^[0-9]+:' | cut -f2 -d' ' | grep -Ev '(lo|tun)')"
  for protocol in $NETS; do
    protocol="$(echo $protocol | sed 's/: *$//m')"

    IIP="$(ip a | grep $protocol | grep inet | sed 's/^ \+//' | cut -f2 -d' ')"
    if [[ "$IIP" != "" ]]; then
      echo "$protocol: $IIP"
    fi
  done
}

echo_uname() {
  echo "nodename: $(uname -n)"
  echo "machine: $(uname -m)"
  echo "operating_system: $(uname -s | tr '[A-Z]' '[a-z]')"
}

echo_architecture() {
  OS="$(uname -s | tr '[A-Z]' '[a-z]')"
  MACHINE="$(uname -m)"
  echo "${OS}-${MACHINE}"
}

kill_selected() {
  PID=$(ps ux | fzf | sed "s/ \+/ /g" | cut -f2 -d" ")
  [[ "$PID" != "" ]] && kill -9 $PID
}

case "$1" in
"path") echo_path ;;
"net") echo_net ;;
"uname") echo_uname ;;
"arch") echo_architecture ;;
"kill") kill_selected ;;
"h" | "") echo_usage ;;
esac
