#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: text filters and mappers
#

## bootstrap
export BIN=$(readlink -f $0)
export DIR=$(dirname $BIN)
export DDIR="$DIR/tx.d"
export EDITOR=${EDITOR:-vi}
[ -x $HOME/bin/nvim ] && EDITOR=$HOME/bin/nvim
## bootstrap

case "$1" in
"ls")
  cd $DDIR && ls -1 && cd - >/dev/null 2>&1
  ;;
"rm")
  rm -f $DDIR/$2
  ;;
"" | "h" | "help")
  cat $DDIR/help.md
  ;;
"e" | "edit")
  [[ "$2" != "" ]] && $EDITOR $DDIR/$2 || echo " [ERROR] Specify filter name"
  ;;
*)
  NAME=$1
  shift && source $DDIR/$NAME $@
  ;;
esac
