#!/usr/bin/env bash

URL0="https://ya.ru/search/?text=%s"
case "$1" in
  "tg:j")
    URL0="https://translate.google.com/?sl=ja&tl=ru&text=%s&op=translate" ;;
  "ty:j")
    URL0="https://translate.yandex.com/en/?source_lang=ja&target_lang=ru&text=%s" ;;
  "jisho")
    URL0="https://jisho.org/search/%s"
esac

URL=$(echo $URL0 | sed "s/%s/$2/")

open "$URL"

