#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: variables to use in another scripts
#

SDIR="$HOME/var/vars"

ensure_storage() {
  [ ! -d $SDIR ] && mkdir -p $SDIR
}

get_var() {
  NAME=$1
  FNAME="$SDIR/$NAME"
  if [ -f "$FNAME" ]; then
    cat "$FNAME"
  fi
}

set_var() {
  NAME=$1
  VALUE=$2
  FNAME="$SDIR/$NAME"

  if [[ "$VALUE" == "" ]]; then
    [ -f "$FNAME" ] && rm $FNAME
  else
    ensure_storage
    echo "$VALUE" >$FNAME
  fi
}

list_vars() {
  [ ! -d $SDIR ] && return

  cd $SDIR
  for file in $(ls -1); do
    local value=$(cat $file)
    local lines=$(echo $value | wc -l)
    if [[ "$lines" == "1" ]]; then
      echo "$file: $value"
    else
      echo "$file:"
      echo "$value" | sed "s/^/  /"
    fi
  done
  cd - >/dev/null 2>&1
}

usage() {
  echo "Usage:"
  echo " $ var name       # Variable value to stdout"
  echo " $ var name value # Store value for variable"
  echo " $ var name \"\"    # Remove value for variable"
  echo " $ var ls|list    # List variables with values"
}

case "$1" in
"ls" | "list") list_vars ;;
"h" | "help") usage ;;
*)
  if [[ "${#@}" == "1" ]]; then
    get_var "$1"
  elif [[ "${#@}" == "2" ]]; then
    set_var "$1" "$2"
  fi
  ;;
esac
