#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: variables to use in another scripts
#
# Note: do not use in this script custom logging,
#   because it uses var script
#

ROOT_DIR="${VAR_ROOT:-$HOME/var}"
SDIR="$ROOT_DIR/vars"

[[ "$DEBUG" != "" ]] && echo "
ROOT_DIR=${ROOT_DIR}
SDIR=${SDIR}"

ensure_storage() {
  [ ! -d $SDIR ] && mkdir -p $SDIR
}

get_var() {
  NAME=$1
  FNAME="$SDIR/$NAME"
  if [ -f "$FNAME" ]; then
    cat "$FNAME"
  fi
}

set_var() {
  NAME=$1
  VALUE=$2
  FNAME="$SDIR/$NAME"

  if [[ "$VALUE" == "" ]]; then
    [ -f "$FNAME" ] && rm $FNAME
  else
    ensure_storage
    echo "$VALUE" >$FNAME
  fi
}

list_vars() {
  [ ! -d $SDIR ] && return

  cd $SDIR
  for file in $(ls -1); do
    local value=$(cat $file)
    local lines=$(echo -e "$value" | wc -l)
    if [[ "$lines" == "0" ]]; then
      echo -ne ""
    elif [[ "$lines" == "1" ]]; then
      echo "$file: $value"
    else
      echo "$file: |"
      echo "$value" | sed "s/^/  /"
    fi
  done
  cd - >/dev/null 2>&1
}

rm_var() {
  NAME="$1"
  FNAME="$SDIR/$NAME"
  [ -f "$FNAME" ] && rm "$FNAME"
}

store_clip() {
  NAME="$1"
  CLIPBOARD="$(xsel -ob)"
  set_var "$NAME" "$CLIPBOARD"
}

usage() {
  echo "Usage:"
  echo " $ var name        # Variable value to stdout"
  echo " $ var name value  # Store value for variable"
  echo " $ var -d | --delete | rm"
  echo "                   # Remove value for variable"
  echo " $ var -i name     # Store clipboard to variable"
  echo " $ var -l | ls     # List variables with values"
  echo ""
  echo "ENV vars:"
  echo " * VAR_ROOT (\$HOME/var by default) - where to keep variables"
}

case "$1" in
"-l" | "--list" | "ls" | "list")
  if [[ "$(which bat)" != "" ]]; then
    list_vars | bat -lyaml -p
  else
    list_vars
  fi
  ;;
"-d" | "--delete" | "rm")
  shift
  rm_var $@
  ;;
"-i" | "clip")
  shift
  store_clip $@
  ;;
"" | "-h" | "--help" | "h" | "help")
  if [[ "$(which bat)" != "" ]]; then
    usage | bat -lsh -p
  else
    usage
  fi
  ;;
*)
  if [[ "${#@}" == "1" ]]; then
    get_var "$1"
  elif [[ "${#@}" == "2" ]]; then
    set_var "$1" "$2"
  fi
  ;;
esac
