### links
#
# > Minimal tmux config: https://youtu.be/6Jgl5wphD00 
# > Nerdfonts: https://www.nerdfonts.com/cheat-sheet
# > Nordtheme: https://www.nordtheme.com/ 
# > TmuxNavigator: https://github.com/christoomey/vim-tmux-navigator

#{{{ characters
terminal_01=""
terminal_02=""

tmux_icon=""

monitor_icon="󰍹"
small_dot=""
small_shevron=""
#}}}

#{{{ colors
night_400="#2e3440"
night_300="#3b4252"
night_200="#434c5e"
night_100="#4c566a"

snow_100="#d8dee9"
snow_200="#e5e9f0"
snow_300="#eceff4"

frost_100="#8fbcbb"
frost_200="#88c0d0"
frost_300="#8aa1c1"
frost_400="#5e81ac"

aurora_red="#bf616a"
aurora_green="#a3be8c"
aurora_yellow="#ebcb8b"
#}}}

### terminal
set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

### bindings
## prefix

unbind C-b
set-option -g prefix C-space

## reload
bind-key r source ~/.tmux.conf \; display-message "» Got you"

## navigation
# * https://github.com/christoomey/vim-tmux-navigator
#
## in vim?
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Move between panes/VIM splits
#
bind-key -n 'M-h' if-shell "$is_vim" 'send-keys M-h'  'select-pane -L'
bind-key -n 'M-j' if-shell "$is_vim" 'send-keys M-j'  'select-pane -D'
bind-key -n 'M-k' if-shell "$is_vim" 'send-keys M-k'  'select-pane -U'
bind-key -n 'M-l' if-shell "$is_vim" 'send-keys M-l'  'select-pane -R'

# Move to previous pane/VIM split
#
# bind-key -n 'M-o' if-shell "$is_vim" 'send-keys M-o'  'select-pane -l'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'M-h' select-pane -L
bind-key -T copy-mode-vi 'M-j' select-pane -D
bind-key -T copy-mode-vi 'M-k' select-pane -U
bind-key -T copy-mode-vi 'M-l' select-pane -R

### Status
set -g status-position top
set -g status-left-length 100

set -g status-style "fg=${snow_100},bg=${night_400}"
set -g status-left \
  "#[fg=${frost_100}]${terminal_01}  #[fg=${aurora_green}]#S#[fg=${snow_100}]${small_shevron} "
set -g status-right "#[fg=${frost_200}]#H #[fg=${snow_100}]${small_dot} #[fg=${night_100}]%Y.%m.%d %H:%M"
set -g window-status-current-format "#[fg=${frost_100},underscore]#I:#W"
set -g window-status-format "#[fg=${night_100}]#I:#W"

### Windows
bind-key c neww -c "#{pane_current_path}"
bind-key n next
bind-key p prev

### Splits
bind-key C-j splitw -v -c "#{pane_current_path}"
bind-key C-l splitw -h -c "#{pane_current_path}"
bind-key C-w kill-pane
bind-key C-space rotate-window
bind-key C-x popup -E ax sync

bind-key j choose-tree -Z

set -g pane-border-lines heavy
set -g pane-border-status off
set -g pane-border-style "fg=${night_200}"
set -g pane-active-border-style "fg=${frost_100}"

set -g automatic-rename off
# set -g window-status-separator "#[fg=${night_100}]"
set -g window-status-separator " "

set-option -g renumber-windows on
set-option -g base-index 1

set-window-option -g mouse on

### System messages colors
set -g message-style "fg=${frost_100},bg=${night_400}"
set -g mode-style "fg=${night_300},bg=${frost_100}"
