#!/usr/bin/env bash

SHORTCUTS_FILE="$DF_DIR/dconf/keyboard-shortcuts.dconf"
SHORTCUTS_PATH="/org/cinnamon/desktop/keybindings/"

check_for_dconf() {
  [[ "$(which dconf)" == "" ]] && (echo "dconf not found"; exit 1)
}

run_export() {
  mkdir -p "$DF_DIR/dconf"
  dconf dump "$SHORTCUTS_PATH" >$SHORTCUTS_FILE
}

run_import() {
  if [ -f $SHORTCUTS_FILE ]; then
    cat $SHORTCUTS_FILE | dconf load "$SHORTCUTS_PATH"
  fi
}

check_for_dconf

case "$1" in
  "export") run_export ;;
  "import") run_import ;;
  "debug") cat $SHORTCUTS_FILE ;;
esac
