#!/usr/bin/env bash

DF_TARGET=$1
[ ! -d $DF_TARGET ] && mkdir -p $DF_TARGET
if [ -d $DF_TARGET ]; then
  debug "Exporing keys to $DF_TARGET..."
  # Export gpg private key
  #
  gpg --output $DF_TARGET/private.pgp --armor --export-secret-key

  debug "Copy jino host config"
  [ -f $HOME/.ssh/hosts/jino ] && cp $HOME/.ssh/hosts/jino $DF_TARGET/jino.host

  debug "Try to copy jino ssh keys"
  [ -f $HOME/.ssh/jino_rsa.pub ] && cp $HOME/.ssh/jino_rsa.pub $DF_TARGET/jino.pub
  [ -f $HOME/.ssh/jino_rsa ] && cp $HOME/.ssh/jino_rsa $DF_TARGET/jino.pri

  debug "Copy github host config"
  [ -f $HOME/.ssh/hosts/github ] && cp $HOME/.ssh/hosts/github $DF_TARGET/github.host

  debug "Try to copy github ssh keys"
  [ -f $HOME/.ssh/github_rsa.pub ] && cp $HOME/.ssh/github_rsa.pub $DF_TARGET/github.pub
  [ -f $HOME/.ssh/github_rsa ] && cp $HOME/.ssh/github_rsa $DF_TARGET/github.pri
fi
