#!/usr/bin/env bash

DF_TARGET=$1

import_host_and_keys() {
  NAME=$1
  if [ -f $DF_TARGET/$NAME.host ]; then
    debug "Importing $NAME host config"
    cp $DF_TARGET/$NAME.host $HOME/.ssh/hosts/$NAME

    debug "Copying keys for $NAME"
    PUB=$DF_TARGET/$NAME.pub
    PRI=$DF_TARGET/$NAME.pri
    [ -f $PUB ] && cp $PUB $HOME/.ssh/$NAME_rsa.pub
    [ -f $PRI ] && cp $PRI $HOME/.ssh/$NAME_rsa
  fi
}

if [ -f $DF_TARGET/private.pgp ]; then
  debug "Importing keys from $DF_TARGET..."
  gpg --import $DF_TARGET/private.pgp
fi

mkdir -p $HOME/.ssh/hosts

import_host_and_keys "jino"
import_host_and_keys "github"
import_host_and_keys "gitlab"
