#!/usr/bin/env bash

commit_message() {
  echo "Sync from $HOSTNAME at $(date +'%y.%m.%d -- %H:%M')"
}

cd $DF_DIR
DF_NOTHING_TO_COMMIT=$(nothing_to_commit)
if [[ "$DF_NOTHING_TO_COMMIT" == "0" ]]; then
  git add .
  case "$1" in
    "e"|"edit")
      git commit --edit -m "$(commit_message)"
      ;;
    *)
      git commit -m "$(commit_message)"
      ;;
  esac
fi
git pull origin master
git push origin master
