#!/usr/bin/env bash

__try_to() {
  COMMAND=$1
  MESSAGE=$2

  echo -ne "${MESSAGE}.."
  OUTPUT="$(eval $COMMAND 2>&1)"
  if [[ "$?" == "0" ]]; then
    echo "done"
  else
    echo " > GOT ERRORS"
    echo -e "\033[31;1m$OUTPUT\033[0m"
  fi
}

commit_message() {
  echo "Sync from $HOSTNAME at $(date +'%d.%m.%Y -- %H:%M')"
  if [[ "$1" != "" ]]; then
    echo ""
    echo "$@"
  fi
}

nothing_to_commit() {
  git status . | grep "nothing to commit" | wc -l
}

cd $REPO_DIR
DF_NOTHING_TO_COMMIT=$(nothing_to_commit)
if [[ "$DF_NOTHING_TO_COMMIT" == "0" ]]; then
  git add .
  COMMIT_MSG=$(commit_message)
  case "$1" in
  "e" | "edit")
    git commit --edit -m "$COMMIT_MSG"
    ;;
  "")
    __try_to "git commit -m '$COMMIT_MSG'" "Comitting changes"
    ;;
  *)
    git commit -m "$(commit_message $@)"
    ;;
  esac
fi
__try_to "git pull origin master" "Pulling changes from github"
__try_to "git push origin master" "Pushing changes to github"
