#!/usr/bin/env bash

source "$DIR/fn/try"

commit_message() {
  echo "Sync from $HOSTNAME at $(date +'%d.%m.%Y -- %H:%M')"
  if [[ "$1" != "" ]]; then
    echo ""
    echo "$@"
  fi
}

nothing_to_commit() {
  git status . | grep "nothing to commit" | wc -l
}

echo -e " » Synchronizing dotfiles"

cd $REPO_DIR
DF_NOTHING_TO_COMMIT=$(nothing_to_commit)
if [[ "$DF_NOTHING_TO_COMMIT" == "0" ]]; then
  git add .
  COMMIT_MSG=$(commit_message)
  case "$1" in
  "e" | "edit")
    git commit --edit -m "$COMMIT_MSG"
    ;;
  "")
    __try_to "git commit -m '$COMMIT_MSG'" "Comitting changes"
    ;;
  *)
    git commit -m "$(commit_message $@)"
    ;;
  esac
fi
__try_to "git pull origin master" "Pulling changes from github"
if [[ "$DF_NOTHING_TO_COMMIT" == "0" ]]; then
  __try_to "git push origin master" "Pushing changes to github"
fi
