---
- name: Copy bashrc
  copy:
    src: "{{ playbook_dir }}/files/bash/rc"
    dest: "/home/{{ user.name }}/.bashrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Copy profile
  copy:
    src: "{{ playbook_dir }}/files/bash/profile.sh"
    dest: "/home/{{ user.name }}/.profile"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Create profile directory
  file:
    path: "/home/{{ user.name }}/.config/profile.d/"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "755"
