---
# * fzf
#   * установка из github
#   * fzf на таб
#     * получение скрипта из репозитория
#     * обновление в случае чего

- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Check if fzf is installed
  stat:
    path: "/home/{{user.name}}/bin/fzf"
  register: "fzf_binary"

- name: Install fzf as github release
  when: "not fzf_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    fzf_version: "0.54.3"
    fzf_repository: "https://github.com/junegunn/fzf"
    fzf_architecture: "linux_amd64"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: "{{ fzf_repository }}/releases/download/v{{ fzf_version }}/fzf-{{ fzf_version }}-{{ fzf_architecture }}.tar.gz"
        copy_src: "{{ ghr_tmp_dir }}/fzf"
        copy_dest: "{{ ghr_install_dir}}/fzf"
        extract_dir: ""

- name: Create config dir
  file:
    path: "/home/{{ user.name }}/.config/fzf"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Link completion script
  file:
    src: "{{playbook_dir}}/files/fzf/fzf.completion"
    dest: "/home/{{ user.name }}/.config/fzf/fzf.completion"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: "link"
