---
# git settings
#  * config
#  * global ignore
#
- name: Copy git config
  copy:
    src: ../../files/git/gitconfig
    dest: "/home/{{ user.name }}/.gitconfig"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Copy git global ignore
  copy:
    src: ../../files/git/gitignore
    dest: "/home/{{ user.name }}/.gitignore"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Install github executable
  package:
    name: gh

- name: Install delta diff viewer
  include_role:
    name: "ansible-role-github-release"
  vars:
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-gnu.tar.gz
        copy_src: "{{ ghr_tmp_dir }}/delta"
        copy_dest: "{{ ghr_install_dir }}/delta"
        extract_dir: "delta-0.18.2-x86_64-unknown-linux-gnu"
