---
# git settings
#  * config
#  * global ignore
#
- name: Create git config directory
  file:
    path: "/home/{{ user.name }}/.config/git"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Copy git config
  copy:
    src: ../../files/git/gitconfig
    dest: "/home/{{ user.name }}/.config/git/config"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Copy git global ignore
  copy:
    src: ../../files/git/gitignore
    dest: "/home/{{ user.name }}/.config/git/ignore"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Set profile link
  file:
    src: "{{ playbook_dir }}/files/git/profile"
    dest: "/home/{{ user.name }}/.config/profile.d/git"
    state: "link"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Install github executable
  package:
    name: gh

- name: Install delta diff viewer
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: https://github.com/dandavison/delta/releases/download/0.18.2/delta-0.18.2-x86_64-unknown-linux-gnu.tar.gz
        extract_dir: "{{ ghr_tmp_dir }}/delta"
        copy_src: "{{ ghr_tmp_dir }}/tmp/delta/delta-0.18.2-x86_64-unknown-linux-gnu/delta"
        copy_dest: "{{ ghr_install_dir }}/delta"

