---
# git settings
#  * config
#  * global ignore
#
- name: Create git config directory
  file:
    path: "/home/{{ user.name }}/.config/git"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Copy git config
  copy:
    src: ../../files/git/gitconfig
    dest: "/home/{{ user.name }}/.config/git/config"
    state: "link"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Copy git global ignore
  copy:
    src: "{{playbook_dir}}/files/git/gitignore"
    dest: "/home/{{ user.name }}/.config/git/ignore"
    state: "link"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Set profile link
  file:
    src: "{{ playbook_dir }}/files/git/profile"
    dest: "/home/{{ user.name }}/.config/profile.d/git"
    state: "link"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Install github executable
  package:
    name: gh

- name: Check if delta viewer installed
  stat:
    path: "/home/{{ user.name }}/bin/delta"
  register: "delta_binary"

- name: Install delta diff viewer
  when: "not delta_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    delta_version: "0.18.2"
    delta_architecture: "x86_64-unknown-linux-gnu"
    delta_repository: "https://github.com/dandavison/delta"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: "{{ delta_repository }}/releases/download/{{ delta_version }}/delta-{{ delta_version }}-{{ delta_architecture }}.tar.gz"
        extract_dir: "{{ ghr_tmp_dir }}/delta"
        copy_src: "{{ ghr_tmp_dir }}/tmp/delta/delta-{{ delta_version }}-{{ delta_architecture }}/delta"
        copy_dest: "{{ ghr_install_dir }}/delta"
