---
# LF settings
#   * settings rc
#   * colors
#   * icons
#
# @link: https://github.com/gokcehan/lf/wiki/Colors-and-Icons
#
- name: Mkdir for lf rc
  file:
    path: "/home/{{ user.name }}/.config/lf"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Copy LF rc file
  copy:
    src: "{{ playbook_dir }}/files/lf/rc"
    dest: "/home/{{ user.name }}/.config/lf/lfrc"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "644"

- name: Copy icons file
  copy:
    src: "{{playbook_dir}}/files/lf/icons.example"
    dest: "/home/{{ user.name }}/.config/lf/icons"

- name: Copy colors file
  copy:
    src: "{{ playbook_dir }}/files/lf/colors.example"
    dest: "/home/{{ user.name }}/.config/lf/colors"

- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Copy LF previewer
  copy:
    src: "{{playbook_dir}}/files/lf/previewer.sh"
    dest: "/home/{{ user.name }}/bin/lf-preview.sh"
    mode: "644"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Check if lf is installed
  stat:
    path: "/home/{{ user.name }}/bin/lf"
  register: "lf_binary"

- name: Install lf as github release
  when: "not lf_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    lf_version: "r33"
    lf_architecture: "linux-amd64"
    lf_repository: "https://github.com/gokcehan/lf"
    owner: "{{ user.name }}"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: "{{ lf_repository }}/releases/download/{{ lf_version }}/lf-{{ lf_architecture }}.tar.gz"
        copy_src: "{{ ghr_tmp_dir }}/lf"
        copy_dest: "{{ ghr_install_dir}}/lf"
        extract_dir: ""
