---
- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Check if neovim installed
  stat:
    path: "/home/{{ user.name }}/bin/nvim"
  register: "nvim_binary"

- name: Install neovim as github release
  when: "not nvim_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    nvim_version: "0.11.0"
    nvim_arch: "linux-x86_64"
    nvim_repository: "https://github.com/neovim/neovim"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      # https://github.com/neovim/neovim/releases/download/v0.11.0/nvim-.appimage
      - url: "{{ nvim_repository }}/releases/download/v{{ nvim_version }}/nvim-{{nvim_arch}}.appimage"
        copy_src: "{{ ghr_tmp_dir }}/nvim-{{nvim_arch}}.appimage"
        copy_dest: "{{ ghr_install_dir}}/nvim"

- name: Set neovim config link
  file:
    src: "{{ playbook_dir }}/files/nvim/config/"
    dest: "/home/{{ user.name }}/.config/nvim"
    state: link
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Set neovim profile and aliases
  file:
    src: "{{ playbook_dir }}/files/nvim/profile"
    dest: "/home/{{ user.name }}/.config/profile.d/nvim"
    state: link
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: Set neovim snippets link
  file:
    src: "{{ playbook_dir }}/files/nvim/snippets/"
    dest: "/home/{{ user.name }}/.config/snippets"
    state: "link"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
