---

- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Check if neovim installed
  stat:
    path: "/home/{{ user.name }}/bin/nvim"
  register: "nvim_binary"

- name: Install neovim as github release
  when: "not nvim_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    nvim_version: "0.10.2"
    nvim_repository: "https://github.com/neovim/neovim"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
    - url: "{{ nvim_repository }}/releases/download/{{ nvim_version }}/nvim.appimage"
      copy_src: "{{ ghr_tmp_dir }}/nvim.appimage"
      copy_dest: "{{ ghr_install_dir}}/nvim"

- name: Install packer.nvim
  become_user: "{{ user.name }}"
  git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "/home/{{ user.name }}/.local/share/nvim/site/pack/packer/start/packer.nvim"

- name: Set neovim config link
  file:
    src: "{{ playbook_dir }}/files/nvim/"
    dest: "/home/{{ user.name }}/.config/nvim"
    state: link
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
