- name: Create profile directory
  file:
    path: "/home/{{ user.name }}/.config/profile.d/"
    state: "directory"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "755"

- name: Link profile files
  file:
    src: "{{ playbook_dir }}/files/bash/profile/{{ item }}"
    dest: "/home/{{ user.name }}/.config/profile.d/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: "link"
  with_items:
    - aliases
    - browser
    - bind
    - direnv
    - editor
    - fasd
    - fzf
    - node
    - path
    - ssh
    - vivid
    - xdg
