---
# * starship
#   * конфигурация в files
#   * скрипт для получения иконки в ~/bin

- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Check if starship is installed
  stat:
    path: "/home/{{ user.name }}/bin/starship"
  register: "starship_binary"

- name: Install starship as github release
  when: "not starship_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    starship_version: "1.21.1"
    starship_repository: "https://github.com/starship/starship"
    starship_arch: "i686-unknown-linux-musl"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: "{{ starship_repository }}/releases/download/v{{ starship_version }}/starship-{{ starship_arch }}.tar.gz"
        owner: "{{ user.name }}"
        copy_src: "{{ ghr_tmp_dir }}/starship"
        copy_dest: "{{ ghr_install_dir }}/starship"
        extract_dir: ""

- name: Copy starship config
  copy:
    src: "../../files/starship/starship.toml"
    dest: "/home/{{ user.name }}/.config/starship.toml"

- name: Copy starship profile
  copy:
    src: ../../files/starship/profile.sh
    dest: "/home/{{ user.name }}/.config/profile.d/starship"

- name: Copy icon script
  copy:
    src: ../../files/starship/icon
    dest: "/home/{{ user.name }}/bin/icon"
