---
# text utilities
#
#  * fd
#  * ripgrep
#
- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- name: Install ripgrep
  package:
    name: "ripgrep"

- name: Install releases
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{ user.name }}"
    ghr_install_dir: "/home/{{ user.name }}/bin"
    ghr_releases:
      - url: https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-i686-unknown-linux-musl.tar.gz
        owner: "{{ user.name }}"
        copy_src: "{{ ghr_tmp_dir }}/fd-v10.1.0-i686-unknown-linux-musl/fd"
        copy_dest: "{{ ghr_install_dir }}/fd"
        extract_dir: ""
      - url: https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-musl-v0.10.1.zip
        owner: "{{ user.name }}"
        copy_src: "{{ ghr_tmp_dir }}/bin/exa"
        copy_dest: "{{ ghr_install_dir }}/exa"
        extract_dir: ""
      - url: https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-i686-unknown-linux-musl.tar.gz
        owner: "{{ user.name }}"
        copy_src: "{{ ghr_tmp_dir }}/bat-v0.24.0-i686-unknown-linux-musl/bat"
        copy_dest: "{{ ghr_install_dir }}/bat"
        extract_dir: ""
