---
# text utilities
#
#  TODO: move each tool into separate text/{toolname}.yml
#    * task to check whether tool is installed
#    * first task to install tool
#    * second task to configure tool
#
- name: Mkdir for bin scripts
  file:
    path: "/home/{{ user.name }}/bin"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"

- include_tasks: ./text/ripgrep.yml
- include_tasks: ./text/fd.yml
- include_tasks: ./text/jless.yml
- include_tasks: ./text/eza.yml
- include_tasks: ./text/bat.yml
- include_tasks: ./text/hurl.yml
