---
# youtube download binary
- name: Mkdir for releases
  when: "ansible_nodename in gui_workstations"
  file:
    path: "/home/{{user.name}}/bin/releases"
    recurse: true
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: directory
    mode: "755"
- name: Check if ytdl already installed
  stat:
    path: "/home/{{user.name}}/bin/releases/ytdl"
  register: "ytdl_binary"
- name: Install ytdl release
  when: "ansible_nodename in gui_workstations and not ytdl_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{user.name}}"
    ytdl_repo: "https://github.com/yt-dlp/yt-dlp"
    ytdl_version: "2025.04.30"
    ghr_install_dir: "/home/{{user.name}}/bin/releases"
    ghr_releases:
      - url: "{{ytdl_repo}}/releases/download/{{ytdl_version}}/yt-dlp_linux"
        owner: "{{user.name}}"
        copy_src: "{{ghr_tmp_dir}}/yt-dlp_linux"
        copy_dest: "{{ghr_install_dir}}/ytdl"
- name: Link from bin to bin/release
  when: "ansible_nodename in gui_workstations"
  file:
    src: "/home/{{user.name}}/bin/releases/ytdl"
    dest: "/home/{{user.name}}/bin/ytdl"
    owner: "{{user.name}}"
    group: "{{user.name}}"
    state: "link"
