# https://github.com/obsidianmd/obsidian-releases/releases/download/v1.8.9/Obsidian-1.8.9.AppImage
- name: Check if obsidian is installed
  stat:
    path: "/home/{{user.name}}/bin/obsidian"
  register: "obsidian_link"

- name: Download obsidian appimage
  vars:
    obsidian_version: "1.8.9"
    obsidian_repo: "https://github.com/obsidianmd/obsidian-releases"
  when: "not obsidian_link.stat.exists"
  get_url:
    url: "{{obsidian_repo}}/releases/download/v{{obsidian_version}}/Obsidian-{{obsidian_version}}.AppImage"
    dest: "/home/{{user.name}}/bin/appimages/Obsidian-{{obsidian_version}}.AppImage"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "755"

- name: "Link to obsidian appimage"
  when: "not obsidian_link.stat.exists"
  vars:
    obsidian_version: "1.8.9"
  file:
    src: "/home/{{user.name}}/bin/appimages/Obsidian-{{obsidian_version}}.AppImage"
    dest: "/home/{{user.name}}/bin/obsidian"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: "link"
