# BAT to show code with highlight
#
# Get from releases page, config, set env
#
# @link: https://github.com/sharkdp/bat
# @link: https://github.com/sharkdp/bat/releases/latest
#
# Colorization theme nord

- name: Check if bat is installed
  stat:
    path: "/home{{user.name}}/bin/bat"

- name: Check if bat is installed
  stat:
    path: "/home/{{user.name}}/bin/bat"
  register: "bat_binary"

- name: Install bat release
  when: "not bat_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{user.name}}"
    bat_version: "0.24.0"
    bat_arch: "i686-unknown-linux-musl"
    bat_repo: "https://github.com/sharkdp/bat"
    ghr_install_dir: "/home/{{user.name}}/bin"
    ghr_releases:
      - url: "{{bat_repo}}/releases/download/v{{bat_version}}/bat-v{{bat_version}}-{{bat_arch}}.tar.gz"
        owner: "{{user.name}}"
        copy_src: "{{ghr_tmp_dir}}/bat-v{{bat_version}}-{{bat_arch}}/bat"
        copy_dest: "{{ghr_install_dir}}/bat"
        extract_dir: ""

- name: Link bat profile
  file:
    src: "{{playbook_dir}}/files/bat/profile"
    dest: "/home/{{user.name}}/.config/profile.d/bat"
    owner: "{{user.name}}"
    group: "{{user.name}}"
    state: "link"
