- name: Check if hurl is installed
  stat:
    path: "/home/{{user.name}}/bin/hurl"
  register: "hurl_binary"

- name: Install hurl release
  when: "not hurl_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{user.name}}"
    hurl_version: "6.0.0"
    hurl_arch: "x86_64-unknown-linux-gnu"
    hurl_repo: "https://github.com/Orange-OpenSource/hurl"
    hurl_dirname: "hurl-{{hurl_version}}-{{hurl_arch}}"
    ghr_install_dir: "/home/{{user.name}}/bin"
    ghr_releases:
      - url: "{{hurl_repo}}/releases/download/{{hurl_version}}/{{hurl_dirname}}.tar.gz"
        extract_dir: ""
        copy_src: "{{ghr_tmp_dir}}/{{hurl_dirname}}/bin/hurl"
        copy_dest: "{{ ghr_install_dir }}/hurl"
