# @link: https://github.com/sibprogrammer/xq
#
# Инструмент для получения содержимого xml-файлов
#  -n чтобы получить узлы как есть, в противном случае будет только текст
#  -x чтобы использовать xpath запрос
#
# А, да, в принципе эта штука доступна из apt-репозитария,
#  но там ерунда какая-то версии 0.0.0, без ключа -n
#  Короче, меня это не устраивало.

- name: Check if xq is installed
  stat:
    path: "/home/{{user.name}}/bin/xq"
  register: "xq_binary"

- name: Install xq release
  when: "not xq_binary.stat.exists"
  include_role:
    name: "ansible-role-github-release"
  vars:
    owner: "{{user.name}}"
    xq_version: "1.3.0"
    xq_arch: "linux_amd64"
    xq_repo: "https://github.com/sibprogrammer/xq"
    ghr_install_dir: "/home/{{user.name}}/bin"
    ghr_releases:
      - url: "{{xq_repo}}/releases/download/v{{xq_version}}/xq_{{xq_version}}_{{xq_arch}}.tar.gz"
        copy_src: "{{ghr_tmp_dir}}/xq"
        copy_dest: "{{ghr_install_dir}}/xq"
        extract_dir: ""
