#!/usr/bin/env tmux
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# SEEALSO: https://www.youtube.com/watch?v=6Jgl5wphD00

TMUX_CFG=$HOME/.config/tmux
TMUX_FILE=alternate.conf
source $TMUX_CFG/$TMUX_FILE
