scripts:
  - ai
  - aid
  - aid.py
  - alt-j
  - ansi
  - ax
  - b
  - browse
  - be
  - chooser
  - codef
  - fl
  - gateway
  - gd
  - kk
  - launch
  - lc
  - note
  - nord
  - opendir
  - pm
  - the
  - tmux-status
  - tx
  - yn
  - var
  - vp
  - x
  - xtm
  - nc
  - zed-copy-lines
  - urlo
  - onsave
  - gi
  - token
  - si
  - osid
  - shps
  - :q
  - :on
  - gls
rust_scripts:
  - wf
  - pe
  - rx
  - kana-converter
  - smartlist
