scripts:
  - aid
  - alt-j
  - ax
  - b
  - be
  - browse
  - chooser
  - fl
  - gateway
  - gd
  - launch
  - lc
  - note
  - nord
  - opendir
  - pe
  - pm
  - the
  - tmux-status
  - tx
  - yn
  - vp
  - x
  - xtm
  - nc
