#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: download shedevrum file

source $DIR/fn/try

TARGET_DIR="$HOME/Pictures/shedevrum/$(date +%Y%m%d)"
URL=$(xsel -o)
YANDEX_HOST="masterpiecer-images.s3.yandex.net"
COUNT=$(echo $1 | grep "$YANDEX_HOST" | wc -l)

__replace_index() {
  echo "$1" | sed "s/:[0-9]/:$2/"
}

__host_available() {
  ping -c1 "$YANDEX_HOST" >/dev/null 2>/dev/null
  [[ "$?" == "0" ]]
}

if [[ "$COUNT" != "0" ]]; then
  if __host_available; then
    mkdir -p "$TARGET_DIR"
    cd "$TARGET_DIR"

    IDX=$(echo $URL | sed "s/^.*://")

    if [[ "$IDX" == "1" && "$SINGLE" != "yes" ]]; then
      __header "Loading images from shed"
      __start "Loading images to file://$TARGET_DIR\nProgress: "

      for idx in $(seq 1 6); do
        IURL=$(__replace_index $URL $idx)
        ITARGET=$(echo $IURL | sed "s/.*\//\.\//; s/:/_/; s/$/\.jpg/")

        wget $IURL -O $ITARGET 2>/dev/null >/dev/null
        __step
      done
      echo -n " "
      __ok
    else
      __header "Loading file from shed"
      __start "Loading "
      TARGET=$(echo $URL | sed "s/.*\//\.\//; s/:/_/; s/$/\.jpg/")
      wget $URL -O $TARGET 2>/dev/null >/dev/null
      __ok
    fi

    if [[ "$NEMO" != "" ]]; then
      nemo $TARGET_DIR
    fi
  else
    echo "Cannot open $YANDEX_HOST"
  fi
fi
