#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: copy pictures to nomad disk

source $DIR/fn/try

if aid.py nomad; then
  __header "Export shedevrum files to nomad disk"
  aid.py move \
    "/home/$USER/Pictures/shedevrum/" \
    "images/shedevrum"
fi
