#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: download shedevrum file

source $DIR/fn/try

TARGET_DIR="$HOME/Pictures/shedevrum/$(date +%Y%m%d)"
URL=$(xsel -o)
COUNT=$(echo $1 | grep "masterpiecer-images.s3.yandex.net" | wc -l)

__replace_index() {
  echo "$1" | sed "s/:[0-9]/:$2/"
}

if [[ "$COUNT" != "0" ]]; then
  mkdir -p "$TARGET_DIR"
  cd "$TARGET_DIR"

  IDX=$(echo $URL | sed "s/^.*://")

  if [[ "$IDX" == "1" && "$SINGLE" != "yes" ]]; then
    __header "Loading images from shed"
    __start "Loading images "

    for idx in $(seq 1 6); do
      IURL=$(__replace_index $URL $idx)
      ITARGET=$(echo $IURL | sed "s/.*\//\.\//; s/:/_/; s/$/\.jpg/")

      wget $IURL -O $ITARGET 2>/dev/null >/dev/null
      __step
    done
    echo -n " "
    __ok
  else
    __header "Loading file from shed"
    __start "Loading "
    TARGET=$(echo $URL | sed "s/.*\//\.\//; s/:/_/; s/$/\.jpg/")
    wget $URL -O $TARGET 2>/dev/null >/dev/null
    __ok
  fi

  if [[ "$NEMO" != "" ]]; then
    nemo $TARGET_DIR
  fi
fi
