#!/bin/bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: get utf-8 icon
#
# Dependencies:
#   * /etc/issue
#   * sed
#
# See also:
#   * Nerdfonts cheatsheet: https://www.nerdfonts.com/cheat-sheet
#

ICON_FOX="🦊"
ICON_LINUX_MINT=" "
ICON_LINUX_UBUNTU=" "
ICON_LINUX_DEBIAN=""
ICON_LINUX_UNKNOWN=" "
ICON_LINUX_FEDORA=" "

LOG_INFO=" "
LOG_ERROR=" "
LOG_WARNING=" "
LOG_DEBUG=" "

__linux_is() {
  COUNT=$(cat /etc/issue | grep "$1" | wc -l)
  [[ "$COUNT" == "1" ]]
}

__linux_release() {
  if [ -f /etc/issue ]; then
    if __linux_is "Mint"; then
      echo "linuxmint"
    elif __linux_is "Ubuntu"; then
      echo "ubuntu"
    elif __linux_is "Debian"; then
      echo "debian"
    elif __linux_is "Fedora"; then
      echo "fedora"
    else
      echo "unknown"
    fi
  else
    echo "unknown"
  fi
}

# Icon for linux distribution
#
linux_icon() {
  RELEASE=${1:-$(__linux_release)}
  case "$RELEASE" in
    "linuxmint")  echo "$ICON_LINUX_MINT" ;;
    "ubuntu")     echo "$ICON_LINUX_UBUNTU" ;;
    "debian")     echo "$ICON_LINUX_DEBIAN" ;;
    "fedora")     echo "$ICON_LINUX_FEDORA" ;;
    "all") 
      echo "Linux icons:"
      echo "  Mint: $ICON_LINUX_MINT"
      echo "Ubuntu: $ICON_LINUX_UBUNTU"
      echo "Debian: $ICON_LINUX_DEBIAN"
      echo "Fedora: $ICON_LINUX_FEDORA"
      ;;
    *)            echo "$ICON_LINUX_UNKNOWN" ;;
  esac
}

log_icon() {
  case "$1" in
    "info") echo "$LOG_INFO" ;;
    "error") echo "$LOG_ERROR" ;;
    "warn"|"warning") echo "$LOG_WARNING" ;;
    "debug") echo "$LOG_DEBUG" ;;
    "all")
      echo "Log icons:"
      echo " DEBUG: $LOG_DEBUG"
      echo "  INFO: $LOG_INFO"
      echo "  WARN: $LOG_WARNING"
      echo " ERROR: $LOG_ERROR"
      ;;
    *) echo "$LOG_DEBUG" ;;
  esac
}

case "$1" in
  "linux") linux_icon $2 ;;
  "log") log_icon $2 ;;
  *) linux_icon ;;
esac
