#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# Theme for starship
#   imported from oh-my-zsh theme "afowler"
#
# 13.02.2021, kaineer@gmail.com
#
# SEEALSO: https://starship.rs/config/
# SEEALSO: https://www.nerdfonts.com/cheat-sheet

add_newline = false
format = "[󱡶](bold cyan) $hostname${custom.linux}$directory$time$docker_context$git_branch $git_status$nodejs$package\n$character$shell"

[shell]
# symbols:  ν ζ β 
disabled = false
bash_indicator = "bash"
zsh_indicator = "zsh"
nu_indicator = "nush"
format = "[${indicator}]($style)[](cyan) "

[time]
disabled = false
time_format = "%H:%M:%S"
format = "[ $time]($style)"
style = "bold #4c566a"

[custom.linux]
# needs script "icon"
# ~~~~~~~~~~~~~~~~~~~
shell = ["icon", "linux"]
style = "cyan bold"
format = " [$output]($style) "
os = "linux"
when = true

[character]
#### symbols: ❯ ✔ ✖  󰡅 
success_symbol="[](green)"
error_symbol="[](red)"

[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "white bold"

[directory]
format = "[$path]($style)"
truncation_length = 3
truncate_to_repo = true
style = "green"
truncation_symbol = '…/'

[docker_context]
format="\nvia [$symbol$context]($style)"
symbol="🐳 "
detect_extensions=[]
style="blue bold"
disabled=false

[git_branch]
symbol = " "
style = "yellow"
format = "\n[$symbol$branch]($style)"

[git_status]
style = "214"
format = "[$all_status]($style)"

[nodejs]
format = "\n[$symbol$version]($style)"
not_capable_style = "bold red"
symbol = "󰎙 "

[package]
format = " [$symbol$version]($style)"
style = "bold 202"
