---
- name: Install missing packages
  package:
    name: "{{ system_packages }}"
    state: "present"

- name: Remove unnecessary packages
  package:
    name: "{{ obsolete_packages }}"
    state: "absent"

- name: Create bin directory
  ansible.builtin.file:
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
    path: '/home/{{ user.name }}/bin'
    state: 'directory'

- include_tasks: ./cli/bash.yml
- include_tasks: ./cli/profile.yml
- include_tasks: ./cli/scripts.yml
- include_tasks: ./cli/git.yml
- include_tasks: ./cli/text.yml
- include_tasks: ./cli/tmux.yml
- include_tasks: ./cli/starship.yml
- include_tasks: ./cli/lf.yml
- include_tasks: ./cli/fzf.yml
- include_tasks: ./cli/neovim.yml
- include_tasks: ./cli/node.yml
