# Ghostty
#   download: https://ghostty.org/docs/install/binary
#     (just in case that debian pkg will be available)
#   ansible:
#     command: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
#     apt: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
#

- name: Check if ghostty exists
  command: "which ghostty"
  ignore_errors: true
  register: "ghostty_binary"

- name: Install ghostty from deb release
  when: "ghostty_binary == ''"
  vars:
    gtty_repo: "github.com/mkasberg/ghostty-ubuntu"
    gtty_version: "1.0.1-0"
    gtty_arch: "amd64"
    gtty_ubuntu_version: "22.04"
  apt:
    deb: "https://{{gtty_repo}}/releases/download/{{gtty_version}}-ppa1/ghostty_{{gtty_version}}.ppa1_{{gtty_arch}}_{{gtty_ubuntu_version}}.deb"
