# Ghostty
#   download: https://ghostty.org/docs/install/binary
#     (just in case that debian pkg will be available)
#   ansible:
#     command: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
#     apt: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
#

- name: Check if ghostty exists
  command: "which ghostty"
  ignore_errors: true
  register: "ghostty_which"

- name: Install ghostty from deb release
  when: "ghostty_which.stdout == ''"
  vars:
    gtty_repo: "github.com/mkasberg/ghostty-ubuntu"
    gtty_version: "1.0.1-0"
    gtty_ppa: "ppa4"
    gtty_arch: "amd64"
    gtty_debian_version: "bookworm"
  apt:
    deb: "https://{{gtty_repo}}/releases/download/{{gtty_version}}-{{gtty_ppa}}/ghostty_{{gtty_version}}.{{gtty_ppa}}_{{gtty_arch}}_{{gtty_debian_version}}.deb"

- name: Check ghostty config directory
  stat:
    path: "/home/{{user.name}}/.config/ghostty"
  register: "ghostty_config_directory"

- name: Link ghostty config
  when: "not ghostty_config_directory.stat.exists"
  file:
    src: "{{ playbook_dir }}/files/ghostty/"
    dest: "/home/{{ user.name }}/.config/ghostty"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    state: "link"
