---
- name: Install dconf requirements
  package:
    name:
      - python3-psutil

- name: "{{ item.title }}"
  become_user: "{{ user.name }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    # --- keyboard
    #
    - title: "Set keyboard options"
      key: "/org/gnome/libgnomekbd/keyboard/options"
      value: "['lv3\tlv3:switch', 'compat\tmisc:typo', 'grp\tgrp:caps_toggle']"
    - title: Set keyboard layouts
      key: "/org/gnome/libgnomekbd/keyboard/layouts"
      value: "['us', 'ru']"

    # --- terminal
    #
    - title: "Set terminal font"
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
      value: "'FiraCode Nerd Font 15'"

    - title: Hide terminal menu
      key: "/org/gnome/terminal/legacy/default-show-menubar"
      value: "false"

    - title: Disable terminal check
      key: "/org/gnome/terminal/legacy/always-check-default-terminal"
      value: "false"

    - title: "Set nord palette"
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/palette"
      value: "['#3B3B42425252', '#BFBF61616A6A', '#A3A3BEBE8C8C', '#EBEBCBCB8B8B', '#8181A1A1C1C1', '#B4B48E8EADAD', '#8888C0C0D0D0', '#E5E5E9E9F0F0', '#4C4C56566A6A', '#BFBF61616A6A', '#A3A3BEBE8C8C', '#EBEBCBCB8B8B', '#8181A1A1C1C1', '#B4B48E8EADAD', '#8F8FBCBCBBBB', '#ECECEFEFF4F4']"

    - title: Set text foreground
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
      value: "'#D8D8DEDEE9E9'"

    - title: Set text background
      key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
      value: "'#2E2E34344040'"

