---
- name: Install dconf requirements
  package:
    name:
      - python3-psutil

- name: Set terminal font
  become_user: kaineer
  dconf:
    key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
    value: "'FiraCode Nerd Font 15'"

- name: Hide terminal menu
  become_user: kaineer
  dconf:
    key: "/org/gnome/terminal/legacy/default-show-menubar"
    value: "false"
