---
- name: Install dconf requirements
  package:
    name:
      - python3-psutil

- name: "{{ item.title }}"
  become_user: "{{ user.name }}"
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items:
    # --- keyboard
    #
    - title: "Set keyboard options"
      key: "/org/gnome/libgnomekbd/keyboard/options"
      value: "['lv3\tlv3:switch', 'compat\tmisc:typo', 'grp\tgrp:caps_toggle']"
    - title: Set keyboard layouts
      key: "/org/gnome/libgnomekbd/keyboard/layouts"
      value: "['us', 'ru']"
