#!/usr/bin/env bash

### NOTE: this line means we should not load aliases
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

clip_aliases() {
  alias clip='xsel -b'
}

[ -x /usr/bin/xsel ] && clip_aliases
