#!/usr/bin/env bash

# exa_aliases() {
#   alias ls=exa
# }

bat_aliases() {
  alias cat='bat --style=plain'
}

clip_aliases() {
  alias clip='xsel -b'
}

# [ -x $HOME/bin/exa ] && exa_aliases
[ -x $HOME/bin/bat ] && bat_aliases
[ -x /usr/bin/xsel ] && clip_aliases
