#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#

# Console key bindings

bind_usage() {
  echo "----------------------------------------"
  echo " Ctrl+h     show bindings list"
  echo ""
  if [ "${TMUX}" != "" ]; then
    echo " C+S+Space  start vi-mode"
    echo ""
  fi
  echo " Ctrl+l     clear screen by scrolling"
  echo " Ctrl+u     cd -"
  echo " Ctrl+o     lf"
  echo " Alt+O      nemo ."
  echo " Alt+g      search in dir history and go"
  echo " Alt+H      cd ~"
  echo " Alt+e      vim ."
  echo " Alt+p      select configured project"
  echo " Alt+E      edit projects configuration"
  echo " Alt+b      edit bindings"
  echo " Alt+x      x"
  echo " Alt+t      t"
  echo " Alt+a      t j"
  echo " Alt+n      start nushell"
  echo " Alt+c      t clock"
  echo "----------------------------------------"
}

# TODO: Make those two to modify some bindings_help.sh file

__alt_() {
  local key="$1"
  local action="$2"
  local LINE="bind '\"\\e$1\":\"$action\\n\"'"
  eval "$LINE"
}

__ctrl_() {
  local key="$1"
  local action="$2"
  local LINE="bind '\"\\C-$1\":\"$action\\n\"'"
  eval "$LINE"
}

### BINDINGS ###
#

# __ctrl_ "i" "cdd\n"   "move directory down"
__ctrl_ "O" "lf ."    "open lf filemanager"
__ctrl_ "u" "cd -"  "move directory back"
__ctrl_ "x" "exit"  "exit"

__alt_  "O" "fo ."  "open gui filemanager"
__alt_  "g" "jj"    "select dir from history and go"
__alt_  "H" "cd"    "open home directory"
__alt_  "e" "vim ."
__alt_  "p" "gd"    "open preconfigured project"
__alt_  "E" "gd e"  "edit gd configuration"
__alt_  "b" "profile mod bind" "edit keyboard bindings"
__ctrl_ "h" "bind_usage" "display binded keys"
__alt_  "x" "x"     "list actions, select and run"
__alt_  "t" "t"     "list tmux actions, select and run"
__alt_  "a" "t j"   "list sessions and select"
__alt_  "n" "nu"    "start nushell"
__alt_  "c" "t clock" "show clock"

