#!/bin/bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#

# Console key bindings

export __BIND_USAGE=""

append_command() {
  local key=$1
  local action=$2
  local description=$3

  if [[ "$description" == "" ]]; then
    description=$action
  fi

  line=$(printf " » %-10s %s" "$1" "$description")
  export __BIND_USAGE="$__BIND_USAGE${line}\n"
}

if [ "${TMUX}" != "" ]; then
  append_command "C+S+Space" "start vi-mode"
fi

bind_usage() {
  echo "----------------------------------------"
  echo -ne "$__BIND_USAGE"
  echo "----------------------------------------"
}

__alt_() {
  local key="$1"
  local action="$2"
  local description="$3"
  append_command "Alt+${key}" "$action" "$description"

  local LINE="bind '\"\\e$1\":\"$action\\n\"'"
  eval "$LINE"
}

__ctrl_() {
  local key="$1"
  local action="$2"
  local description="$3"
  append_command "Ctrl+${key}" "$action" "$description"

  local LINE="bind '\"\\C-$1\":\"$action\\n\"'"
  eval "$LINE"
}

### BINDINGS ###
#

# __ctrl_ "i" "cdd\n"   "move directory down"
__ctrl_ "O" "lf ."    "open lf filemanager"
__ctrl_ "u" "cd -"  "move directory back"
__ctrl_ "x" "exit"  "exit"

__alt_  "O" "fo ."  "open gui filemanager"
__alt_  "g" "jj"    "select dir from history and go"
__alt_  "H" "cd"    "open home directory"
__alt_  "e" "nvim ."
__alt_  "p" "gd"    "open preconfigured project"
__alt_  "E" "gd e"  "edit gd configuration"
__alt_  "b" "profile mod bind" "edit keyboard bindings"
__ctrl_ "h" "bind_usage" "display binded keys"
__alt_  "x" "x"     "list actions, select and run"
__alt_  "t" "t"     "list tmux actions, select and run"
__alt_  "a" "t j"   "list sessions and select"

[[ "$(which nu)" != "" ]] && __alt_  "n" "nu"    "start nushell"

__alt_  "c" "t clock" "show clock"

