#!/bin/bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#

[[ "$1" != "-i" ]] && return

# Console key bindings

export __BIND_USAGE=""

append_command() {
  local key=$1
  local action=$2
  local description=$3

  if [[ "$description" == "" ]]; then
    description=$action
  fi

  line=$(printf " » %-10s %s" "$1" "$description")
  export __BIND_USAGE="$__BIND_USAGE${line}\n"
}

bind_usage() {
  echo "----------------------------------------"
  echo -ne "$__BIND_USAGE"
  echo "----------------------------------------"
}

__alt_() {
  local key="$1"
  local action="$2"
  local description="$3"
  append_command "Alt+${key}" "$action" "$description"

  local LINE="bind '\"\\e$1\":\"$action\\n\"'"
  eval "$LINE"
}

__ctrl_() {
  local key="$1"
  local action="$2"
  local description="$3"
  append_command "Ctrl+${key}" "$action" "$description"

  local LINE="bind '\"\\C-$1\":\"$action\\n\"'"
  eval "$LINE"
}

### BINDINGS ###
#

if [ "${TMUX}" != "" ]; then ## TMUX bindings
  append_command "C+S+Space" "start vi-mode"
  __alt_ "c" "t clock" "show clock"
fi

__ctrl_ "o" "lf ." "open lf filemanager"
__ctrl_ "u" "cd -" "move directory back"
__ctrl_ "x" "exit" "exit"

__alt_ "O" "nemo . >/dev/null 2>&1" "open gui filemanager"
__alt_ "g" "jj" "select dir from history and go"
__alt_ "H" "cd" "open home directory"
__alt_ "u" "exa -l" "list current directory"
__alt_ "e" "nvim ."
__alt_ "p" "gd" "open preconfigured project"
__alt_ "E" "gd e" "edit gd configuration"
__ctrl_ "h" "bind_usage" "display binded keys"
__alt_ "x" "x" "list actions, select and run"
__alt_ "t" "t" "list tmux actions, select and run"
__alt_ "a" "t j" "list sessions and select"
__alt_ "s" "serve" "serve directory"
__alt_ ";" "kyo e" "edit current tasks"

[[ "$(which nu)" != "" ]] && __alt_ "n" "nu" "start nushell"
