#!/usr/bin/env bash

### NOTE: this line means we should not load fzf
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

export BROWSER=/usr/bin/brave-browser
export BROWSER_CLASS="brave-browser"
