#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#

[[ "$1" != "-i" ]] && return

if [[ "$(which podman)" != "" ]]; then
  alias dc=podman-compose
  alias d=podman
elif [[ "$(which docker)" == "" ]]; then
  alias dc=docker-compose
  alias d=docker
fi
