#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
#
# Link: https://chat.deepseek.com/a/chat/s/b82e3e82-4b91-434b-8d10-22a8ff851528
# NOTE: обновление podman-compose до версии 1.5.0
#

[[ "$1" != "-i" ]] && return

DOCKER_BIN=""
DOCKER_COMPOSE_BIN=""

### detect compose file
COMPOSE_FILE=""
if [ -f "docker-compose.yml" ]; then
  COMPOSE_FILE="docker-compose.yml"
fi
if [ -f "docker-compose.yaml" ]; then
  COMPOSE_FILE="docker-compose.yaml"
fi
if [ -f "compose.yml" ]; then
  COMPOSE_FILE="compose.yml"
fi
if [ -f "compose.yaml" ]; then
  COMPOSE_FILE="compose.yaml"
fi

if [[ "$(which podman)" != "" ]]; then
  DOCKER_BIN="podman"
  DOCKER_COMPOSE_BIN="podman-compose"

  if [[ "$(which podman-compose)" != "" ]]; then
    alias dc=podman-compose
  fi

  alias d="$DOCKER_BIN"
  alias dps="podman ps"
  alias dpsf='podman ps --format "{{.ID}}|{{.Names}}|{{.Status}}" | awk -F"|" '\''{printf "%-15s | %-25s | %s\n", $1, $2, $3}'\'
  alias dpsi="podman ps --format \"{{.ID}}\""

  dup() {
    if [ -n "$COMPOSE_FILE" ]; then
      SERVICE=$(cat "${COMPOSE_FILE}" | yq -r '.services | keys[]' | fzf -dmenu) 
      "$DOCKER_COMPOSE_BIN" up "$SERVICE" -d
    fi
  }

  dk() {
    LINE=$(podman ps --format "{{.ID}} | {{.Names}}" | fzf -0)
    if [[ "$LINE" != "" ]]; then
      ID=$(echo $LINE | awk '{ print $1 }')
      $DOCKER_BIN kill $ID
      $DOCKER_BIN rm $ID
    fi
  }

  drm() {
    LINE=$(podman ps -a --format "{{.ID}} | {{.Names}}" | fzf -0 -m)
    if [[ "$LINE" != "" ]]; then

      # echo "---"
      # echo "$IDS"
      # echo "---"

      for LL in $(echo "$LINE" | awk '{ print $1 }'); do
        echo -n ""
        echo ":$LL"
        # ID=$(echo $LL | awk '{ print $1 }')
      done
      # ID=$(echo $LINE | awk '{ print $1 }')
      # $DOCKER_BIN kill $ID
      # $DOCKER_BIN rm $ID
    fi
  }
fi

if [[ "$(which docker)" != "" ]]; then
  DOCKER_BIN="docker"
  alias dc=docker-compose
  alias d=docker
  alias drm="docker rm"
  alias dk="docker kill"
  alias dps="docker ps"

  drk() {
    docker kill $@
    docker rm $@
  }
fi
