#!/usr/bin/env bash

### NOTE: this line means we should not load editor env
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

if [ -x "$(command -v nvim)" ]; then
  export EDITOR=nvim
elif [ -x "$(command -v vi)" ]; then
  export EDITOR=vi
fi
