#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
### NOTE: this line means we should not load editor env
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

if [ -x "$(command -v nvim)" ]; then
  export EDITOR=nvim
elif [ -x "$(command -v vi)" ]; then
  export EDITOR=vi
fi
