#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# @link: https://github.com/clvv/fasd

### NOTE: this line means we should not load fasd
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

eval "$(fasd --init posix-hook bash-hook)"

# Самостоятельное определение fasd_cd
fasd_cd() {
  [ $# -gt 1 ] && cd "$(fasd -e echo "$@")" || fasd "$@"
}
alias j='fasd_cd -d'

jg() {
  TARGET=$(fasd -l | fzf)
  [[ "$TARGET" != "" ]] && cd $TARGET
}
