#!/usr/bin/env bash

# @link: https://github.com/clvv/fasd

eval "$(fasd --init posix-alias bash-hook)"

alias j='fasd_cd -d'

jj() {
  TARGET=$(fasd -l | fzf)
  [[ "$TARGET" != "" ]] && cd $TARGET
}
