#!/usr/bin/env bash

eval "$(fzf --bash)"

export FZF_DEFAULT_OPTS="-x --cycle --bind=ctrl-j:accept,tab:toggle-down --info=inline-right"

export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#e5e9f0,bg:#2e3440,hl:#81a1c1,gutter:#2e3440
    --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#81a1c1,separator:#3b4252
    --color=info:#eacb8a,prompt:#a3be8b,pointer:#88c0d0
    --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'
