#!/usr/bin/env bash
#
# * FZF theme sandbox: https://vitormv.github.io/fzf-themes/
# * Nord theme: https://www.nordtheme.com/
#

eval "$(fzf --bash)"

export FZF_DEFAULT_OPTS="-x --bind=ctrl-j:accept,tab:toggle-down --info=inline-right --ellipsis=…"

# Brave Leo generated answer:
# @link: https://search.brave.com/search?q=fzf+history+without+numbers&source=web&summary=1&conversation=cff978e1012acaccd52ee5&summary_og=5b67409c3ff676e826bb83
#
export FZF_CTRL_R_OPTS="--with-nth 2.."

# My nordtheme colors
# export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
#     --color=fg:#e5e9f0,bg:#2e3440,hl:#81a1c1,gutter:#2e3440
#     --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#81a1c1,separator:#3b4252
#     --color=info:#88c0d0,prompt:#a3be8b,pointer:#88c0d0
#     --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#e5e9f0,bg:#2e3440,hl:#ebcb8b,gutter:#2e3440
    --color=fg+:#e5e9f0,bg+:#3b4252,hl+:#ebcb8b,separator:#3b4252
    --color=info:#88c0d0,prompt:#a3be8b,pointer:#88c0d0
    --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'

source $HOME/.config/fzf/fzf.completion
bind -x '"\t": fzf_bash_completion'
