#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#

### NOTE: this line means we should not load fnm
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

export FNM_PATH=$HOME/.fnm
export PATH=$HOME/.local/bin:$PATH

eval "$(fnm env)"
