#!/usr/bin/env bash

### NOTE: this line means we should fix path
###   for non-interactive shell
[[ "$1" == "-i" ]] && return

FIXED_PATH=$(echo $PATH | tr ':' '\n' | grep -v "^$" | sort | uniq | tr '\n' ':')
export PATH=$FIXED_PATH
