#!/usr/bin/env bash

### NOTE: this line means we should fix path
###   for non-interactive shell
[[ "$1" == "-i" ]] && return

# 1. remove duplicates, remove $HOME/bin
# 2. prepend with $HOME/bin

FIXED_PATH=$(echo $PATH | tr ':' '\n' | grep -v "^$" | grep -v "$HOME/bin" | sort | uniq | tr '\n' ':')
export PATH="$HOME/bin:$FIXED_PATH"
