#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: this variable is used by
#  * git config

### NOTE: this line means we should fix path
###   for non-interactive shell
[[ "$1" == "-i" ]] && return

# 1. remove duplicates, remove $HOME/bin
# 2. prepend with $HOME/bin

FIXED_PATH=$(echo $PATH | tr ':' '\n' | grep -v "^$" | grep -v "$HOME/bin" | sort | uniq | tr '\n' ':')
export PATH="$HOME/bin:$FIXED_PATH"
