#!/usr/bin/env bash

### NOTE: this line means we should not load fzf
###   for non-interactive shell
[[ "$1" != "-i" ]] && return

# NOTE: needs keychain, but it should be installed
#   from ansible task

eval "$(keychain --quiet --eval id_rsa)"
