#!/usr/bin/env bash
#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
[[ "$1" != "-i" ]] && return

# NOTE: needs keychain, but it should be installed
#   from ansible task

eval "$(keychain --quiet --eval id_rsa)"
