#!/usr/bin/env bash

reset="\e[0m"

black="\e[0;30m"
red="\e[0;31m"
green="\e[0;32m"
yellow="\e[0;33m"
blue="\e[0;34m"
purple="\e[0;34m"
cyan="\e[0;36m"
white="\e[0;37m"

bold_black="\e[1;30m"
bold_red="\e[1;31m"
bold_green="\e[1;32m"
bold_yellow="\e[1;33m"
bold_blue="\e[1;34m"
bold_purple="\e[1;34m"
bold_cyan="\e[1;36m"
bold_white="\e[1;37m"
