#!/usr/bin/env bash

source "$DIR/fn/colors"

SQ=""

__header() {
  echo -ne "${bold_cyan}## $1"
  echo ""
  echo ""
}

__step() {
  echo -ne "$SQ"
}

__start() {
  MESSAGE=$1
  echo -ne " ${cyan}+${bold_white} ${MESSAGE}${reset}"
}

__ok() {
  echo -e "${bold_green}done${reset}"
}

__failure() {
  echo -e "${bold_red}failure${reset}"
}

__try_to() {
  COMMAND=$1
  MESSAGE=$2

  __start $MESSAGE
  echo -n ".."
  OUTPUT="$(eval $COMMAND 2>&1)"
  if [[ "$?" == "0" ]]; then
    __ok
  else
    __failure
    echo -e " ${bold_yellow}> GOT ERRORS${reset}"
    echo -e " --- OUTPUT ---"
    echo -e "${bold_red}$OUTPUT${reset}"
    exit 1
  fi
}
