#!/usr/bin/env bash

#  _____  ___
# /__   \/ __\  Tangerine Cat, kaineer@gmail.com
#   / /\/ /
#  / / / /___   github: https://github.com/kaineer
#  \/  \____/   twitter: https://twitter.com/kaineer
#
# What: functions to use for output
#
#  * __header "message" to display a message
#  * __start "message" message without CR
#  * __ok -- display "done"
#  * __failure -- display "failure" and exit 1
#  * __try_to "command" "message" -- display message, then try to run command and show ok/failure by $?

source "$DIR/fn/colors"

SQ=""

__header() {
  echo -ne "${bold_cyan}## $1"
  echo ""
  echo ""
}

__step() {
  echo -ne "$SQ"
}

__start() {
  MESSAGE=$1
  echo -ne " ${cyan}+${bold_white} ${MESSAGE}${reset}"
}

__ok() {
  echo -e "${bold_green}done${reset}"
}

__failure() {
  echo -e "${bold_red}failure${reset}"
}

__error() {
  echo -e "${bold_red} * ERROR: $@${reset}"
}

__try_to() {
  COMMAND=$1
  MESSAGE=$2

  __start "$MESSAGE"
  echo -n ".."
  OUTPUT="$(eval $COMMAND 2>&1)"
  if [[ "$?" == "0" ]]; then
    __ok
  else
    __failure
    echo -e " ${bold_yellow}> GOT ERRORS${reset}"
    echo -e " --- OUTPUT ---"
    echo -e "${bold_red}$OUTPUT${reset}"
    exit 1
  fi
}
