#!/usr/bin/env bash

list_media_disks() {
  ls -1 /media/$USER
}

list_locations() {
  echo home
  list_media_disks
}

DIR=$(list_locations | $HOME/bin/chooser -matching fuzzy -p locations)

if [[ "$DIR" != "" ]]; then
  if [[ "$DIR" == "home" ]]; then
    $HOME/bin/opendir $HOME
  else
    $HOME/bin/opendir "/media/$USER/$DIR"
  fi
fi
