#!/usr/bin/env bash

CONFIG_FILE=$HOME/var/dir.json

list_titles() {
  /home/kaineer/bin/gd ls
}

TARGET=$(list_titles | $HOME/bin/chooser -i -matching fuzzy -p "gd")

if [[ "$TARGET" != "" ]]; then
  DIR=$(cat $CONFIG_FILE | jq -r ".[\"${TARGET}\"].dir")
  $HOME/bin/opendir "$DIR"
fi
