#!/usr/bin/env bash

list_recent_files() {
  cat $HOME/.local/share/recently-used.xbel |
    xq -x "/xbel/bookmark/@href" |
    sed "s/file:\/\///"
}

FILE=$(list_recent_files | $HOME/bin/chooser -p "recent files")

if [[ "$FILE" != "" ]]; then
  open $FILE
fi
