#!/usr/bin/env bash

export LAUNCH_TERMINAL=wezterm

case "$LAUNCH_TERMINAL" in
  "wezterm")
    export WEZTERM_BINARY=$HOME/bin/wezterm
    start_or_activate_by_classname "$WEZTERM_BINARY" "org.wezfurlong.wezterm"
    ;;

  "ghostty")
    export GHOSTTY_BINARY=/usr/bin/ghostty
    start_or_activate_by_classname "$GHOSTTY_BINARY" "com.mitchellh.ghostty"
    ;;
esac
