#!/usr/bin/env bash

LAUNCH_TERMINAL="wezterm"

if [[ "$LAUNCH_TERMINAL" == "" ]]; then
  if [[ "$(which alacritty)" != "" ]]; then
    export LAUNCH_TERMINAL="alacritty"
  elif [[ "$(which wezterm)" != "" ]]; then
    export LAUNCH_TERMINAL="wezterm"
  elif [[ "$(which ghostty)" != "" ]]; then
    export LAUNCH_TERMINAL="ghostty"
  fi
fi

case "${LAUNCH_TERMINAL}" in
"ghostty")
  export GHOSTTY_BINARY=/usr/bin/ghostty
  start_or_activate_by_classname "$GHOSTTY_BINARY" "ghostty"
  ;;
"wezterm")
  export WEZTERM_BINARY=$HOME/bin/wezterm
  start_or_activate_by_classname "$WEZTERM_BINARY" "org.wezfurlong.wezterm"
  ;;
"alacritty")
  export ALACRITTY_BINARY=$HOME/bin/alacritty
  start_or_activate_by_classname "$ALACRITTY_BINARY" "Alacritty"
  ;;
esac
