require("core.vim-pack.config")({
  "plugins.colors.pack",
  "plugins.navigation.pack",
  "plugins.telescope.pack",
  "plugins.lsp.pack",
  "plugins.git.pack",
  "plugins.lualine.pack",
  "plugins.completion.pack",
})
