[mgr]

prepend_keymap = [
  { on = "Y", 
    run = 'shell "xclip -selection clipboard -t image/png -i < %s && notify-send yazi \"image is yanked\""', 
    desc = "Копировать изображение" },
  { on = "j", run = 'arrow 1', desc = 'no wrapping for next' },
  { on = "k", run = 'arrow -1', desc = 'no wrapping for prev' },
  { on = "l", run = 'plugin on-enter', desc = 'enter to dir / file' },
]
