[opener]
play-video-cli = [
  { run = "mplayer -noborder %s", orphan = true, desc = "Play video with mplayer" },
]
play-audio-cli = [
  { run = "mplayer %s", desc = "Play audio with mplayer" },
]
jless-view = [
  { run = "/home/kaineer/bin/jless %s" },
]
neovim-edit = [
  { run = "nvim %s" },
]
image-view = [
  { run = "eog -f %s" },
]

[open]
prepend_rules = [
  { mime = "image/*", use = "image-view" },
  { mime = "video/*", use = "play-video-cli" },
  { mime = "audio/*", use = "play-audio-cli" },
  { mime = "application/json", use = ["jless-view", "neovim-edit"] },
  { mime = "image/*", use = "image-view" },
]

[mgr]

sort_by = "mtime"
show_hidden = true
show_symlink = true
